### ISSUE TITLE
[BUG] Failed on executeMultiple code 13

### ISSUE THREAD

**Issue by FelipeSVidal** [sei-protocol/sei-js#115]
**SeiJS package & version**
"@sei-js/core": "^3.1.2"

**Chain ID**
pacific-1

**Describe the bug**
When I try to send executeMultiple, the following message returns: `BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log:`. Log is empty... 

**To Reproduce**
1. Restore wallet, `const wallet = await restoreWallet(SEED_PHRASE)`
2. Get Address, `const addr = (await burnWallet.getAccounts())[0].address`
3. Get signing cliente, `const signingClient = await getSigningCosmWasmClient(RPC_URL, wallet, {
      gasPrice: GasPrice.fromString("0.01usei"),
    });`
4. Execute, `signingClient.executeMultiple(addr, [msgs], "auto")`, msg is: {contractAddress: "", msg: {}}

**Expected behavior**
Execute multiple sends.

**Additional context**
signingClient.simulate using typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract" work propertly

Error trace:
`execute error BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log:
    at SigningCosmWasmClient.broadcastTx (E:\DEV\Coders 85\testSei\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:177:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SigningCosmWasmClient.executeMultiple (E:\DEV\Coders 85\testSei\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:215:24) {
  code: 13,
  codespace: 'sdk',
  log: ''
}`

**Comment by fraggdiller** [comment]
> **SeiJS package & version** "@sei-js/core": "^3.1.2"
> 
> **Chain ID** pacific-1
> 
> **Describe the bug** When I try to send executeMultiple, the following message returns: `BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log:`. Log is empty...
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Restore wallet, `const wallet = await restoreWallet(SEED_PHRASE)`
> 2. Get Address, `const addr = (await burnWallet.getAccounts())[0].address`
> 3. Get signing cliente, `const signingClient = await getSigningCosmWasmClient(RPC_URL, wallet, { gasPrice: GasPrice.fromString("0.01usei"), });`
> 4. Execute, `signingClient.executeMultiple(addr, [msgs], "auto")`, msg is: {contractAddress: "", msg: {}}
> 
> **Expected behavior** Execute multiple sends.
> 
> **Additional context** signingClient.simulate using typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract" work propertly
> 
> Error trace: `execute error BroadcastTxError: Broadcasting transaction failed with code 13 (codespace: sdk). Log: at SigningCosmWasmClient.broadcastTx (E:\DEV\Coders 85\testSei\node_modules\@cosmjs\cosmwasm-stargate\build\cosmwasmclient.js:177:35) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async SigningCosmWasmClient.executeMultiple (E:\DEV\Coders 85\testSei\node_modules\@cosmjs\cosmwasm-stargate\build\signingcosmwasmclient.js:215:24) { code: 13, codespace: 'sdk', log: '' }`

how did you fix that?
