### ISSUE TITLE
TypeError: (0 , _sei_js_core__WEBPACK_IMPORTED_MODULE_11__.connect) is not a function

### ISSUE THREAD

**Issue by truecode112** [sei-protocol/sei-js#129]
I am using sei-js/core in Tyepscript Next.js project.
![image](https://github.com/sei-protocol/sei-js/assets/115639173/4c9fa7c9-9fdd-4241-a9ea-13eb7a65d5a7)
Cannot find connect function.
How to solve this?

**Comment by besated** [comment]
Hi @truecode112, there isn't a `connect` function in `@sei-js/core` anymore. To connect to a wallet, please take a look at the JavaScript reference page in our docs [here](https://docs.sei.io/advanced/javascript-reference#connecting-to-a-wallet).

Apologies for the confusion, the docs are a bit outdated and will be updated soon.
