### ISSUE TITLE
Error: Unregistered type url: /seiprotocol.seichain.dex.MsgPlaceOrders

### ISSUE THREAD

**Issue by ben-razor** [sei-protocol/sei-js#25]
Since the upgrade to @sei-js/core v1.3.0 there is an error when I try to enter orders:

```
Error: Unregistered type url: /seiprotocol.seichain.dex.MsgPlaceOrders
```

The signing client was created like this:

```js
const { accounts, offlineSigner } = await connect('keplr', 'atlantic-2', seiTestnetRest, seiTestnetRPC);

const signingStargateClient = await getSigningClient(
  seiTestnetRPC,
  offlineSigner
);

// registry.types doesn't contain any sei type urls
console.log({registry: signingStargateClient.registry})
```

It looks like the sei types aren't registered. Has the API changed or is there an issue with this version?

**Comment by ben-razor** [comment]
The following code fixes the problem. I'll keep the issue open for a bit as I think the intention might be to automatically do this in getSigningClient as the previous version did.

```js
import { getSigningClient } from '@sei-js/core'
import { cosmosProtoRegistry, seiprotocolProtoRegistry } from '@sei-js/proto'

let protoRegistry = seiprotocolProtoRegistry.concat(cosmosProtoRegistry)

const signingStargateClient = await getSigningClient(
  seiTestnetRPC, 
  offlineSigner, 
  {
    registry: new Registry(protoRegistry)
  }
) 
```

**Comment by besated** [comment]
Thanks for bringing this up! We will be adding this to the Sei Signing Clients by default in the next version. It has been added in #27
