### ISSUE TITLE
staking module query delegation info error

### ISSUE THREAD

**Issue by smithmonnnnnnn** [sei-protocol/sei-js#37]
sei-js/packages/proto/src/codegen/cosmos/staking/v1beta1/query.lcd.ts
The URL in the method delegation is missing a character "/"
now is blow:
async delegation(params: QueryDelegationRequest): Promise<QueryDelegationResponseSDKType> {
    const endpoint = `cosmos/staking/v1beta1/validators/${params.validatorAddr}delegations/${params.delegatorAddr}`;
    return await this.req.get<QueryDelegationResponseSDKType>(endpoint);
  }
maybe it should be :
async delegation(params: QueryDelegationRequest): Promise<QueryDelegationResponseSDKType> {
    const endpoint = `cosmos/staking/v1beta1/validators/${params.validatorAddr}/delegations/${params.delegatorAddr}`;
    return await this.req.get<QueryDelegationResponseSDKType>(endpoint);
  }

**Comment by codebycarson** [comment]
Fixed in PR: https://github.com/sei-protocol/sei-js/pull/50

**Comment by codebycarson** [comment]
@smithmonnnnnnn This has been fixed in @sei-js/proto@1.3.0 and onwards.
