### ISSUE TITLE
When I wrap my app with `SeiWalletProvider` in Nextjs project, it gets some unexpected errors.

### ISSUE THREAD

**Issue by haodev007** [sei-protocol/sei-js#43]
Hello, SEI team!

Thank you for your dedicated efforts and amazing work!

I am a newbie on SEI network and I am building SEI dApp now and integrate all avaialbe SEI wallets to dApp using `@sei-js/react`.
But when I wrap my app with `SeiWalletProvider`, I get unexpected token errors. here is the screenshot to showcase errors.
![image](https://github.com/sei-protocol/sei-js/assets/98631674/9850ae2b-34a2-4936-aee8-f4e9b5d6e0c8)

Here is my code snippets:
![image](https://github.com/sei-protocol/sei-js/assets/98631674/5f26968f-b2f9-475f-998a-bdb20762c3cf)
![image](https://github.com/sei-protocol/sei-js/assets/98631674/49ff6453-e45b-484d-81bb-aa4f1a82c2db)
![image](https://github.com/sei-protocol/sei-js/assets/98631674/3b5bd439-b612-40a0-a238-4fca22cde914)

Will u give me some ideas to solve this issue?
Thanks in advance!

**Comment by codebycarson** [comment]
@haodev007 can you please try the latest version of this package?
