### ISSUE TITLE
New Error!

### ISSUE THREAD

**Issue by EagTf** [sei-protocol/sei-js#63]
Property 'wallets' is missing in type '{ children: Element; chainConfiguration: ChainConfiguration; }' but required in type 'SeiWalletProviderProps'.ts(2741)
types.d.ts(40, 5): 'wallets' is declared here.

whats the format to add the wallets, it isnt in any of your guys guides

**Comment by codebycarson** [comment]
@EagTf this error seems to be with your build environment. We have recently added better bundling recently to help with these issues. Please try the latest version of @sei-js and let us know if you still have issues.
