### ISSUE TITLE
can't import connect  & WalletConnect from '@sei-js/core'

### ISSUE THREAD

**Issue by SteveMBao** [sei-protocol/sei-js#74]
Hello teams, I'm following this [Guide](https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial/frontend-tutorial) to build my frontend page, but it's show this:

![image](https://github.com/sei-protocol/sei-js/assets/17777077/0a1c6cb4-6f12-4b09-bceb-7f78bfd9c451)

**Comment by codebycarson** [comment]
@SteveMBao this issue has been resolved and you can see the updated counter app tutorial here. https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial/frontend-tutorial
