### ISSUE TITLE
Consider re-exporting cosmjs dependencies

### ISSUE THREAD

**Issue by ARitz-Cracker** [sei-protocol/sei-js#80]
`@sei-js/core` has a number of `cosmjs` dependencies. However, in its current form, for us to make anything... functional... including creating our own helper functions or abstractions which take types that originally come from `cosmjs`, we have to import that directly. The main issue with this is that `@sei-js/core` specifies an _exact_ version for its `cosmjs` dependencies, which means _I_ also have to specify an exact version for `cosmjs` dependencies, and _hope_ things don't break with a minor or patch change to `@sei-js/core`.

**Comment by codebycarson** [comment]
Looking into this issue today and we are discussing options internally. Will keep you updated.

**Comment by codebycarson** [comment]
This has been loosened up in the latest @sei-js released. Thank you for bringing this to our attention!

https://github.com/sei-protocol/sei-js/pull/85
